<?php
namespace Smite;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-22 at 02:19:40.
 */
class APITest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var API
     */
    protected $object;

    private $devId = 12345;
    private $authKey = "testauthkey";

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new API($this->devId, $this->authKey);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Smite\API::getDevId
     * @todo   Implement testGetDevId().
     */
    public function testGetDevId()
    {
        $this->assertEquals($this->object->getDevId(), $this->devId);
    }

    /**
     * @covers Smite\API::getAuthKey
     * @todo   Implement testGetAuthKey().
     */
    public function testGetAuthKey()
    {
        $this->assertEquals($this->object->getAuthKey(), $this->authKey);
    }

    /**
     * @covers Smite\API::getGuzzleClient
     * @todo   Implement testGetGuzzleClient().
     */
    public function testGetGuzzleClient()
    {
        $this->assertInstanceOf('GuzzleHttp\Client', $this->object->getGuzzleClient());
    }

    /**
     * @covers Smite\API::preferFormat
     * @todo   Implement testPreferFormat().
     */
    public function testPreferFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smite\API::useLanguage
     * @todo   Implement testUseLanguage().
     */
    public function testUseLanguage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Smite\API::request
     * @todo   Implement testRequest().
     */
    public function testRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
